// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/core/raftlease (interfaces: FSMMetrics)

// Package raftlease is a generated GoMock package.
package raftlease

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockFSMMetrics is a mock of FSMMetrics interface.
type MockFSMMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockFSMMetricsMockRecorder
}

// MockFSMMetricsMockRecorder is the mock recorder for MockFSMMetrics.
type MockFSMMetricsMockRecorder struct {
	mock *MockFSMMetrics
}

// NewMockFSMMetrics creates a new mock instance.
func NewMockFSMMetrics(ctrl *gomock.Controller) *MockFSMMetrics {
	mock := &MockFSMMetrics{ctrl: ctrl}
	mock.recorder = &MockFSMMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFSMMetrics) EXPECT() *MockFSMMetricsMockRecorder {
	return m.recorder
}

// RecordExpirations mocks base method.
func (m *MockFSMMetrics) RecordExpirations(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordExpirations", arg0)
}

// RecordExpirations indicates an expected call of RecordExpirations.
func (mr *MockFSMMetricsMockRecorder) RecordExpirations(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordExpirations", reflect.TypeOf((*MockFSMMetrics)(nil).RecordExpirations), arg0)
}

// RecordOperation mocks base method.
func (m *MockFSMMetrics) RecordOperation(arg0, arg1 string, arg2 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordOperation", arg0, arg1, arg2)
}

// RecordOperation indicates an expected call of RecordOperation.
func (mr *MockFSMMetricsMockRecorder) RecordOperation(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordOperation", reflect.TypeOf((*MockFSMMetrics)(nil).RecordOperation), arg0, arg1, arg2)
}

// StartOperation mocks base method.
func (m *MockFSMMetrics) StartOperation() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartOperation")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// StartOperation indicates an expected call of StartOperation.
func (mr *MockFSMMetricsMockRecorder) StartOperation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartOperation", reflect.TypeOf((*MockFSMMetrics)(nil).StartOperation))
}
